import { LayoutGrid, ClipboardPenLine, FileText, Archive, UserRoundCog, ShieldCheckIcon, SquarePen, CircleX, CircleCheck, CircleAlert, Search, CalendarRange, Trash2, ChartBarStacked, Plus, Save, CircleUserRound, Signature, Eye, Calendar, TimerReset } from "lucide-vue-next"

export default {
    LayoutGrid,
    ClipboardPenLine,
    FileText,
    Archive,
    UserRoundCog,
    ShieldCheckIcon,
    SquarePen,
    CircleX,
    CircleCheck,   
    CircleAlert,
    Search,
    CalendarRange,
    Trash2,
    ChartBarStacked,
    Plus,
    Save,
    CircleUserRound,
    Signature,
    Eye,
    Calendar,
    TimerReset,
}